name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies and Android SDK tools
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-11-jdk python3-pip git python3-setuptools python3-dev build-essential
          pip install --upgrade pip
          pip install cython buildozer

          # Accept licenses
          mkdir -p ~/.android && echo 'count=0' > ~/.android/repositories.cfg
          yes | sdkmanager --licenses

          # Install a stable version of Build Tools and Platform
          yes | sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: dicom-ai-viewer-apk
          path: bin/*.apk
